apiVersion: v1
clusters:
- cluster:
    server: https://10.235.26.60:6443
    insecure-skip-tls-verify: true
  name: conductor-mi35x
contexts:
- context:
    cluster: conductor-mi35x
    user: iree-dev
  name: conductor-mi35x
current-context: conductor-mi35x
users:
- name: iree-dev
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ3akNCcXdJVUhaaThIRjd1RGhveFhOODNnU1JpSTlPbmsza3dEUVlKS29aSWh2Y05BUUVMQlFBd0ZURVQKTUJFR0ExVUVBeE1LYTNWaVpYSnVaWFJsY3pBZUZ3MHlOakF5TVRFeU1qQTRNakJhRncweU56QXlNVEV5TWpBNApNakJhTUNFeEVUQVBCZ05WQkFNTUNHbHlaV1V0WkdWMk1Rd3dDZ1lEVlFRS0RBTmhiV1F3S2pBRkJnTXJaWEFECklRQkIzcWRpSVFGSHB0L0J1R3N2d3hRM01pVzZqaHovcFVJdUZudFhIUHRNd1RBTkJna3Foa2lHOXcwQkFRc0YKQUFPQ0FRRUFFU0tHY1dqNUhhQmxtcGRQVjlkSWZJUDJIZm92UEZRQWZzNHQ5ZjVFb0c0SUxHVG9DU285cldRbQpqckVyUkxXbERWdzJkZkxSMVYydUtVQ3V0SDEycS9PbmtONHVqQThqbG9OSW1kQS9VVWlUME9RRzZzUmJKQ0RKCkVpUElqT1RObGE2YzZnOVJNYmZMbXRPZHpDVzdXUXNKTUdJU0tFbGxDQVBGa1JUTHNDbzNQNjJlS1FqbGU1LzcKL2RZcmtUN3NtWjdwYVh1Qlp4REJZMno3bjRWSFFDcEpPRjJkNG9GYjBzV0wyRFd1T0ZqdW9ZUjA2TVZ2MkNtbgozZGZFOFh4U1NCaWRvdUh6R3ZOSGRsSG50QjNHcklEVHZ5QlVhNkVna2IweUVIZDlZSDVlWkZYcVBwdEZPWGZiCkxuTjN0QVlVWktHSFlHQlRoKzMzclBPYjMwL2ZRZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    client-key-data: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1DNENBUUF3QlFZREsyVndCQ0lFSUY5OXprV0oyV05hNE85MEtxSnlDUlZZTjExRi8wcDd1QjIyTGpYYjl3Z2QKLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo=
